/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AdminArticles: () => import('#controllers/admin_articles_controller'),
  AdminCategories: () => import('#controllers/admin_categories_controller'),
  Admin: () => import('#controllers/admin_controller'),
  ArticleRatings: () => import('#controllers/article_ratings_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Public: () => import('#controllers/public_controller'),
  Session: () => import('#controllers/session_controller'),
}
